package br.senai.sp.jandira.model;

public enum Estados {

	SAO_PAULO, MINAS_GERAIS, RIO_DE_JANEREIRO, ESPIRITO_SANTO, 
	RIO_GRANDE_DO_SUL, SANTA_CANTARINA, PARANA, 
	AMAZONAS, ACRE, RORAIMA, PARA, RONDONIA, AMAPA
	
}
